#apiVersion: v1
#kind: Service
#metadata:
#  name: stickersng-api
#  labels:
#    app: stickersng-api
#spec:
#  ports:
#  - port: 8000
#  selector:
#    app: stickersng-api
#    tier: backend-api
#  type: LoadBalancer
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: stickersng-api
#  labels:
#    app: stickersng-api
#spec:
#  ports:
#  - port: 8000
#  selector:
#    app: stickersng-api
#    tier: backend-api
#  type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: stickersng-api
  labels:
    app: stickersng-api
spec:
  type: NodePort
  ports:
  - nodePort: 32223
    port: 8000
    name: stickersng-api
  - port: 3306
    name: stickersng-mysql
  selector:
    app: stickersng-api
    tier: backend-api
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: stickersng-api
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stickersng-api
  labels:
    app: stickersng-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stickersng-api
      tier: backend-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stickersng-api
        tier: backend-api
    spec:
      initContainers:
      - name: setup-storage
        image: busybox
        command: ["sh", "-c", "mkdir -p /var/www/html/storage/framework/views/ && mkdir -p /var/www/html/storage/framework/cache/ && mkdir -p /var/www/html/storage/framework/sessions/ && chown -R www-data:www-data /var/www/html/storage/framework/sessions/"]
        volumeMounts:
        - name: stickersng-api-persistent-storage
          mountPath: /var/www/html/storage
      containers:
      - image: jusis707/lav:13
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 200m
            memory: 256Mi
          env:    # get environment variables from secrets
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: stng-secrets
                  key: dbName
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: stng-secrets
                  key: dbUserNameKey
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stng-secrets
                  key: dbPasswordKey
        name: stickersng-api
        envFrom:
        - secretRef:
            name: stng-secrets
        ports:
        - containerPort: 8000
          name: stickersng-api
        volumeMounts:
        - name: stickersng-api-persistent-storage
          mountPath: /var/www/html/storage
      volumes:
      - name: stickersng-api-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
