apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: stng-secrets
stringData:
  DB_HOST: "c3RpY2tlcnNuZy1teXNxbA=="
  DB_DATABASE: "c3RpY2tlcnNuZy1kYg=="
  DB_USERNAME: "c3RpY2tlcnNuZw=="
  DB_PASSWORD: "c3RpY2tlcnNuZw=="
  
